services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - rede_creditos

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_MESSAGE_MAX_BYTES: 20000000
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 20000000
      KAFKA_CFG_FETCH_MESSAGE_MAX_BYTES: 20000000      
    networks:
      - rede_creditos
      
  postgres:
    image: postgres:15
    container_name: postgres_creditos
    environment:
      POSTGRES_DB: creditosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5437:5432'
    volumes:
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rede_creditos
  backend:
    build: ./backend
    container_name: backend_creditos
    depends_on:
      - postgres
      - kafka
    ports:
      - '8080:8080'
    networks:
      - rede_creditos

  frontend:
    build: ./frontend
    container_name: frontend_creditos
    ports:
      - '4200:80'
    depends_on:
      - backend
    networks:
      - rede_creditos

volumes:
  postgres_data:

networks:
  rede_creditos:
    driver: bridge